# Generated by Django 3.1 on 2020-09-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='KeyWords',
        ),
        migrations.AddField(
            model_name='metadata',
            name='keyWords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
